name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/JiraService/
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/JiraService/
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/JiraService/JiraService.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 