name: Publish Nuget Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/JiraService.sln
    - name: Build
      run: dotnet build --no-restore src/JiraService.sln
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/AtlassianAssistance.JiraService/AtlassianAssistance.JiraService.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
